<a href="https://colab.research.google.com/github/travisvj/Python_Demo_01_040525/blob/main/lesson13_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [1]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.84206126, 0.07649444, 0.46109859, 0.49541307],
       [0.27939382, 0.80723578, 0.26553102, 0.99265798],
       [0.251657  , 0.98869678, 0.91011205, 0.69876852]])

In [2]:
from numpy.random import normal

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [3]:
#ndarray,陣列運算
normal_value * 10

array([[12.3362727 , -5.04943281,  3.92559827,  7.28702926],
       [ 1.52128202, -0.13458133, -4.64948296,  2.51511797],
       [-2.07227929,  5.63830731, -3.28773824, -7.8891162 ]])

In [4]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([ 1.84994674, -0.07476643, -0.76108264])